#include "pch.h"
#include "BgLabelControl.h"
#include "BgLabelControl.g.cpp"

// Note: This file was automatically generated by a tool, based on the .idl
// file for the class, during compilation. The generated files are in
// the Generated Files\sources directory. Copy the file, delete the warning and 
// modify as necessary to complete your implementation.

namespace winrt::SimpleComponent::implementation
{
    Microsoft::UI::Xaml::DependencyProperty BgLabelControl::m_labelProperty =
        Microsoft::UI::Xaml::DependencyProperty::Register(
            L"Label",
            winrt::xaml_typename<winrt::hstring>(),
            winrt::xaml_typename<SimpleComponent::BgLabelControl>(),
            Microsoft::UI::Xaml::PropertyMetadata{ winrt::box_value(L"default label"), Microsoft::UI::Xaml::PropertyChangedCallback{ &BgLabelControl::OnLabelChanged } }
        );

    void BgLabelControl::OnLabelChanged(Microsoft::UI::Xaml::DependencyObject const& d, Microsoft::UI::Xaml::DependencyPropertyChangedEventArgs const& /* e */)
    {
        if (SimpleComponent::BgLabelControl theControl{ d.try_as<SimpleComponent::BgLabelControl>() })
        {
            // Call members of the projected type via theControl.

            SimpleComponent::implementation::BgLabelControl* ptr{ winrt::get_self<SimpleComponent::implementation::BgLabelControl>(theControl) };
            // Call members of the implementation type via ptr.
        }
    }
}
